src/app/app.module.ts
src/app/components/info-tooltip/info-tooltip.component.html
src/app/components/info-tooltip/info-tooltip.component.scss
src/app/components/info-tooltip/info-tooltip.component.spec.ts
src/app/components/info-tooltip/info-tooltip.component.ts
src/app/components/tooltip/tooltip.component.html
src/app/components/tooltip/tooltip.component.scss
src/app/components/tooltip/tooltip.component.spec.ts
src/app/components/tooltip/tooltip.component.ts
src/app/index/start-form/start-form.component.html
src/app/index/start-form/start-form.component.scss
src/app/index/start-form/start-form.component.ts
src/app/services/coingecko-api/coingecko-api.service.spec.ts
src/app/services/coingecko-api/coingecko-api.service.ts
src/app/services/instant-trade/types/InstantTrade.ts
src/app/services/instant-trade/uni-swap-service/uni-swap.service.ts
src/app/services/instant-trade/uni-swap-service/uniswap-service.service.spec.ts
src/app/services/web3Api/web3-api.service.ts
src/assets/i18n/en.json

Rubic 74(uni swap)

---

src/app/features/swaps-page/instant-trades/components/instant-trades-form/instant-trades-form.component.scss
src/app/shared/components/use-custom-token/custom-token-form.component.scss

Мобильная вёрстка инстант трейдов для use custom token

RUBIC-355-instant

---

src/app/features/bridge-page/components/bridge/bridge.component.scss
src/app/features/order-book-trade-page/components/order-book-trade/components/token-form/token-form.component.html
src/app/features/swaps-page/instant-trades/components/instant-trades-form/instant-trades-form.component.html
src/app/features/swaps-page/instant-trades/components/instant-trades-form/instant-trades-form.component.scss
src/app/features/swaps-page/order-books/components/order-books-form/order-books-form-options/order-books-form-options.component.scss
src/app/features/swaps-page/order-books/components/order-books-form/order-books-form.component.html
src/app/features/swaps-page/order-books/components/order-books-form/order-books-form.component.scss
src/app/features/swaps-page/page-module/components/swaps-page-component/swaps-page.component.scss
src/app/features/swaps-page/trades-module/components/trades-form/trades-form.component.scss
src/app/shared/components/collaborations/collaborations.component.scss
src/app/shared/components/footer/footer.component.scss
src/app/shared/components/input-dropdown/input-dropdown.component.scss
src/app/shared/components/modal/modal.component.html
src/app/shared/components/modal/modal.component.scss
src/app/shared/components/primary-button/primary-button.component.scss
src/app/shared/components/tokens-input/tokens-input.component.scss
src/app/shared/components/tokens-table/tokens-table.component.scss
src/app/shared/components/use-custom-token/custom-token-form.component.scss
src/app/shared/components/volume-block/volume-block.component.scss
src/scss/elements/_dialog.scss
src/scss/elements/_dropdown-labels.scss
src/styles.scss

Заменил обратно плейсходлеры на материал
У кнопки не было марджинов, просто на мобилке убрал трансформ при состоянии active
Уменьшил шрифты у кнопок на мобильном разрешении.
На других языках вроде все ок выглядит

Rubic 355 instant

---

src/app/core/header/components/header/components/user-profile/user-profile.component.ts
src/app/core/header/services/header.store.ts
src/app/features/bridge-page/components/brifge-form/bridge-form.component.scss
src/app/features/swaps-page/instant-trades/components/instant-trades-form/instant-trades-form.component.scss
src/app/features/swaps-page/order-books/components/order-books-form/order-books-form.component.scss
src/app/features/swaps-page/page-module/components/swaps-page-component/swaps-page.component.scss
src/app/shared/components/input-dropdown/input-dropdown.component.scss
src/app/shared/components/tokens-input/tokens-input.component.scss
src/app/shared/components/tokens-table/components/tokens-accordion/tokens-accordion.component.scss
src/scss/_vars.scss

Mobile fix styles

---

src/app/features/swaps-page/instant-trades/components/instant-trades-form/instant-trades-form.component.html
src/app/shared/components/token-input/blockchain-select.component.scss

fix font for select cross-chain swaps and placeholder at instant-trades

hotfix-RUBIC-433

---

src/app/core/header/models/languages-list.ts
src/app/features/bridge-page/components/bridge/bridge.component.html
src/app/features/swaps-page/page-module/components/swaps-page-component/swaps-page.component.html
src/app/shared/components/disclaimer-text/disclaimer-text.component.html
src/assets/i18n/en-new.json
src/assets/i18n/es-new.json
src/assets/i18n/ko-new.json
src/assets/i18n/ko.json

Add new structure for Korean translate and little bit translation for some words

RUBIC-421: New structure for Korean translate

---

.husky/_/husky.sh
src/app/app.component.ts
src/app/core/header/models/languages-list.ts
src/assets/i18n/ru-new.json
src/assets/i18n/zh-new.json
src/assets/i18n/zh.json

Add new strucure translation for russian and chinese

Rubic 421 russian and chinese new structure translation 

---

src/app/features/swaps-page/instant-trades/components/instant-trades-form/instant-trades-form.component.scss

add margin to gas-fee for best rate

fix best rate space

---

src/app/core/services/http/http.service.ts

Hotfit coingecko request

---

src/app/core/services/http/http.service.ts

Hotfix coingecko request

---

src/app/shared/components/tokens-input/token-label/token-label.component.html
src/app/shared/components/tokens-input/token-label/token-label.component.scss

fix images

---

src/app/features/cross-chain-swaps-page/bridge-page/components/brifge-form/bridge-form.component.ts

fix bridge select toBlockchain ETH after XDAI

Fix bridges xdai bug

---

src/app/features/cross-chain-swaps-page/bridge-page/components/brifge-form/bridge-form.component.ts

fix bug with xdai network in bridges

Hotfix bridges

---

src/app/core/header/components/header/components/header-navigation/header-navigation.component.html
src/app/features/swaps-page/instant-trades/components/instant-trades-form/components/tokens-swap-input/tokens-swap-input.component.html
src/index.html

Fix SEO Author

---

src/app/core/header/components/header/header.component.scss
src/scss/_taiga-slyles.scss

radius and margin for notifications

fix banner

---

src/app/features/crypto-tap/components/crypto-tap-form/crypto-tap-form.component.html
src/app/features/tokens-select/components/blockchains-aside/blockchains-aside.component.html

https://docs.google.com/document/d/1luCPU2jARcjkA2p2NhX5sa6IK2YOScfvCCvxcCyp_8s/edit

fix index for gtm

---

angular.json
src/app/features/bridge/components/bridge-bottom-form/bridge-bottom-form.component.ts
src/app/features/crypto-tap/components/crypto-tap-form/crypto-tap-form.component.ts
src/app/features/instant-trade/services/instant-trade-service/instant-trade.service.ts
src/app/shared/components/success-tx-modal/success-tx-modal.component.html
src/app/shared/components/success-tx-modal/success-tx-modal.component.ts
src/app/shared/constants/modals/modal-config.ts
src/assets/analytics/google-analytics.js
src/assets/i18n/en.json
src/assets/i18n/es.json
src/assets/i18n/ko.json
src/assets/i18n/ru.json
src/assets/i18n/zh.json
src/index.html

1. Убрать ссылку на MyTrades для крипто тэп модалки
2. оставить гугл аналитику только на проде
3. Комменты, issue (Дима)
4. Правки от Сергея
- Заменить ngOnDestroy на taiga ui destroyer
- Не делать подписки в Constructor 
- Имплементированть интерфейс OnInit 
- Вынести 5 секунд в константу
5. Вынести аналитику только для продакшена

Analytics prod and comment fixes

---

src/app/features/swaps/components/swaps-settings/settings-ccr/settings-ccr.component.html
src/app/features/swaps/components/swaps-settings/settings-ccr/settings-ccr.component.ts

Set default slippage for cross chain - 2

Set default slippage for cross chain

---

src/app/shared/components/rubic-tokens/rubic-tokens.component.scss

Back max button visible for widget

Fix max button for widget

---

src/app/shared/components/success-tx-modal/success-tx-modal.component.ts
src/app/shared/constants/modals/modal-config.ts

https://docs.google.com/spreadsheets/d/1D18yzoO_SqgQpbywrQPmBkPn-5eNxYYI8mTAkOYX4lQ/edit#gid=1982230834
Вернул таймер для модального окна после подписи транзакции

Timer for progress modal

---

package-lock.json
package.json
src/app/core/services/blockchain/wallets/wallet-connector-service/wallet-connector.service.ts

https://rubicans.youtrack.cloud/agiles/121-6/current?issue=RUBIC-75

my-trades wrong wallet error

---

src/app/features/bridge/components/bridge-bottom-form/bridge-bottom-form.component.ts
src/app/features/cross-chain-routing/components/cross-chain-routing-bottom-form/cross-chain-routing-bottom-form.component.ts
src/app/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
src/app/features/instant-trade/services/instant-trade-service/instant-trade.service.ts
src/app/features/swaps/services/success-tx-modal-service/success-tx-modal.service.ts
src/app/features/tokens-select/components/tokens-list/tokens-list.component.scss
src/app/shared/components/success-tx-modal/success-tx-modal.component.html
src/app/shared/components/success-tx-modal/success-tx-modal.component.ts
src/assets/i18n/en.json
src/assets/i18n/es.json
src/assets/i18n/ko.json
src/assets/i18n/ru.json
src/assets/i18n/zh.json
src/scss/_taiga-slyles.scss

YouTrack:
https://rubicans.youtrack.cloud/agiles/121-6/current?issue=RUBIC-92

Rubic 92/change notification modal

---

src/app/features/cross-chain-routing/services/cross-chain-routing-service/constants/near/near-ccr-view-methods.ts
src/app/features/cross-chain-routing/services/cross-chain-routing-service/constants/solana/raydium-ccr-sctuct.ts
src/app/features/cross-chain-routing/services/cross-chain-routing-service/contracts-data/contract-data/near-contract-data.ts
src/app/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts

change moonriver rpc links [master]

Fix crypto fee in NEAR [DEVELOP]

---

src/app/features/cross-chain-routing/components/cross-chain-routing-bottom-form/cross-chain-routing-bottom-form.component.scss
src/app/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.scss
src/app/features/instant-trade/components/providers-panels/components/provider-panel/provider-panel.component.scss
src/app/features/swaps/components/amount-input/components/token-amount-input/token-amount-input.component.scss
src/app/features/swaps/components/swaps-form/swaps-form.component.scss
src/app/shared/components/token-amount-estimated/token-amount-estimated.component.scss

Fix view of token amount and layout of iframe

Fix view of iframe

---

src/app/core/rubic-footer/models/footer-links.ts

upd discord link

---

src/scss/_libs.scss

Исправил цвет фона у текста при подключении кошелька coinbase.

fix text bg

---

src/app/shared/constants/blockchain/networks.ts

Switch fantom nodes [DEV]

---

src/app/core/services/auth/auth.service.ts
src/app/core/wallets/components/wallets-modal/wallets-modal.component.ts

Настроил аналитику при успешном ручном подключении кошелька.

fix connect wallet ga

---

src/app/core/services/external-api/coingecko-api/coingecko-api.service.ts

Coingecko enterprise api [Dev]

---

src/app/features/swaps/features/cross-chain-routing/services/cross-chain-routing-service/celer/celer.service.ts

Fix token decimals in target network

---

src/app/app.component.ts
src/app/core/services/query-params/models/query-params.ts
src/app/core/services/query-params/query-params.service.ts
src/app/features/swaps/features/main-form/components/platform-tokens-amount/platform-tokens-amount.component.scss
src/styles.scss

Сокрытие лишних элементов при использовании формы обмена через iframe.

hide unused ui for iframe

---

src/app/features/swaps/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts

Disable near [DEV]

---

src/app/shared/constants/blockchain/networks.ts

Fix ankr rpc [DEV]

---

package.json
yarn.lock

Update rubic sdk version [DEV]

---

package.json
src/app/core/recent-trades/models/common-trade.ts
src/app/features/swaps/features/cross-chain-routing/services/cross-chain-routing-service/cross-chain-routing.service.ts
src/app/features/swaps/features/instant-trade/components/instant-trade-bottom-form/instant-trade-bottom-form.component.ts
src/app/features/swaps/features/instant-trade/services/instant-trade-service/instant-trade.service.ts
src/app/features/swaps/features/main-form/components/swap-info/components/cross-chain-bridge-swap-info/components/cross-chain-swap-info/cross-chain-swap-info.component.html
yarn.lock

Update rubic sdk version [MASTER]

Small fixes [D]

---

src/app/core/header/services/header.store.ts
src/app/core/wallets/components/wallets-modal/wallets-modal.component.scss
src/app/features/swaps/features/main-form/components/amount-input/components/token-amount-input/token-amount-input.component.scss
src/app/features/swaps/features/main-form/components/amount-input/components/user-balance-container/user-balance-container.component.scss

Правки для iframe на лендинге.
Исправил работу query параметра isDesktop.
Поправил размеры окна с выбором кошелька.
Чтобы избежать скролла, изменил положение кнопки "You have ... MAX".

Rubic 388/fix iframe for seo

---

src/app/features/earn/components/statistics/statistics.component.scss

Поправил отступы и шрифты в блоке Overview.

fix mobile template

---

src/app/features/earn/services/staking.service.ts

Исправил баг с кнопкой MAX в форме создания нового депозита.

fix stake btn

---

.github/workflows/cd-widget-production.yml
src/app/core/services/backend/tokens-api/tokens-api.service.ts

Fix tokens search

---

src/app/core/rubic-footer/models/footer-links.ts
src/assets/images/contacts/dune.svg
src/assets/images/contacts/dune_light.svg

Добавил в footer ссылку на rubic-dashboard в Dune.

add Dune link

---

src/app/core/rubic-footer/models/footer-links.ts
src/assets/images/contacts/dune.svg
src/assets/images/contacts/dune_light.svg

Добавил в footer ссылку на rubic-dashboard в Dune.

Rubic 703/add dune

---

src/app/features/earn/components/stake-form/stake-form.component.ts

Исправил баг, при котором нельзя было застейкать больше 9.999 BRBC.

convert amount to BigNumber

---

src/app/features/earn/components/stake-form/stake-form.component.ts

Исправил баг, при котором нельзя было застейкать больше 9.999 BRBC.

Rubic 654/fix staking amount error

---

src/app/features/earn/components/stake-form/stake-form.component.ts

fix max button error

---

src/app/features/earn/components/stake-form/stake-form.component.ts

Rubic 654/fix staking max btn

---

src/app/features/swaps/features/main-form/components/swap-info/components/instant-trade-swap-info/instant-trade-swap-info.component.html
src/app/features/swaps/features/main-form/components/swap-info/components/instant-trade-swap-info/instant-trade-swap-info.component.ts

Исправил отображение Slippage в ИТ свапах, из числа перевёл в проценты.

Fix slippage

---

src/app/features/swaps/features/main-form/components/swap-info/components/cross-chain-bridge-swap-info/components/cross-chain-swap-info/cross-chain-swap-info.component.ts

Поправил баг с отображением кнопки с высоким Price Impact для symbiosis при свапе RBC.

fix price impact bug

---

package.json
yarn.lock

Fix wrong routing while non proxy swap

Fix wrong routing while non proxy swap

---

package.json
src/app/features/swaps/features/cross-chain/services/cross-chain-calculation-service/cross-chain-calculation.service.ts
yarn.lock

Removed ChangeNow from SeN program.
Add ref address for XY reauest.

removed ChangeNow from SeN program

---

package.json
yarn.lock

Fix multichain

---

package.json
yarn.lock

Fix typo in de.json

---

src/app/features/swaps/features/onramper-exchange/services/onramper-widget.service.ts

Add wallet address to partner context

Add wallet address to partner context

---

package.json
src/app/features/swaps/features/cross-chain/services/cross-chain-calculation-service/cross-chain-calculation.service.ts
src/app/features/swaps/features/instant-trade/services/instant-trade-service/instant-trade.service.ts
yarn.lock

rubic-1948

---

package.json
yarn.lock

Fix EON routing
